#!/usr/bin/env bun
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const PACKAGE_MANIFEST = "package.json"
const PLUGIN_MANIFEST = "plugins/immune-brain/.claude-plugin/plugin.json"
const PLUGIN_VERSION_MODULE = "plugins/immune-brain/runtime/plugin_version.ts"
const SEMVER_RE = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
const TAG_RE = /^immune-brain-v(?<version>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*))$/

class VersionError extends Error {}

class SemVer {
  constructor(public major: number, public minor: number, public patch: number) {}
  static parse(value: string): SemVer {
    const match = SEMVER_RE.exec(value)
    if (!match) throw new VersionError(`Invalid SemVer: ${value}`)
    return new SemVer(Number(match[1]), Number(match[2]), Number(match[3]))
  }
  compare(other: SemVer): number {
    return this.major - other.major || this.minor - other.minor || this.patch - other.patch
  }
  toString(): string { return `${this.major}.${this.minor}.${this.patch}` }
}

function usage(): never {
  console.error("usage: plugin_versioning.ts [--repo-root <path>] {stamp | validate [--tag <immune-brain-vX.Y.Z>]}")
  process.exit(2)
}

function parseGlobalArgs(argv: string[]): { root: string; rest: string[] } {
  let root = "."
  const rest: string[] = []
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--repo-root") {
      if (i + 1 >= argv.length) usage()
      root = argv[++i]
    } else rest.push(argv[i])
  }
  return { root: resolve(root), rest }
}

function readManifest(path: string): any {
  try { return JSON.parse(readFileSync(path, "utf8")) }
  catch (error: any) { throw new VersionError(`Malformed JSON in ${path}: ${error.message}`) }
}
function writeManifest(path: string, manifest: any): void {
  writeFileSync(path, JSON.stringify(manifest, null, 2) + "\n", "utf8")
}
function manifestPath(root: string, rel: string): string { return resolve(root, rel) }

function packageVersion(root: string): string {
  const manifest = readManifest(manifestPath(root, PACKAGE_MANIFEST))
  if (typeof manifest.version !== "string") throw new VersionError(`Missing string version in ${PACKAGE_MANIFEST}`)
  SemVer.parse(manifest.version)
  return manifest.version
}

function requirePluginPath(root: string): string {
  const path = manifestPath(root, PLUGIN_MANIFEST)
  if (!existsSync(path)) throw new VersionError(`Missing ${PLUGIN_MANIFEST}`)
  return path
}

function renderPluginVersionModule(version: string): string {
  return `// Generated by scripts/plugin_versioning.ts from the root package.json.\nexport const PLUGIN_VERSION = ${JSON.stringify(version)} as const;\n`
}

export function stampPluginManifest(root = "."): { version: string; files: string[] } {
  const version = packageVersion(root)
  const path = requirePluginPath(root)
  const plugin = readManifest(path)
  plugin.version = version
  writeManifest(path, plugin)
  writeFileSync(manifestPath(root, PLUGIN_VERSION_MODULE), renderPluginVersionModule(version), "utf8")
  return { version, files: [PLUGIN_MANIFEST, PLUGIN_VERSION_MODULE] }
}

export function loadManifestVersions(root = "."): Record<string, string> {
  const version = packageVersion(root)
  const path = requirePluginPath(root)
  const plugin = readManifest(path)
  if (typeof plugin.version !== "string") throw new VersionError(`Missing string version in ${PLUGIN_MANIFEST}`)
  SemVer.parse(plugin.version)
  if (plugin.version !== version) throw new VersionError(`${PLUGIN_MANIFEST} version ${plugin.version} does not match ${PACKAGE_MANIFEST} ${version}`)
  const versionModule = manifestPath(root, PLUGIN_VERSION_MODULE)
  if (!existsSync(versionModule)) throw new VersionError(`Missing ${PLUGIN_VERSION_MODULE}`)
  if (readFileSync(versionModule, "utf8") !== renderPluginVersionModule(version)) {
    throw new VersionError(`${PLUGIN_VERSION_MODULE} does not match ${PACKAGE_MANIFEST} ${version}`)
  }
  return {
    [PACKAGE_MANIFEST]: version,
    [PLUGIN_MANIFEST]: plugin.version,
    [PLUGIN_VERSION_MODULE]: version,
  }
}

export function versionFromTag(tag: string): SemVer {
  const match = TAG_RE.exec(tag)
  if (!match?.groups?.version) throw new VersionError(`Invalid release tag: ${tag}; expected immune-brain-vX.Y.Z`)
  return SemVer.parse(match.groups.version)
}

export function validateManifests(root = ".", tag?: string): any {
  const versions = loadManifestVersions(root)
  const version = SemVer.parse(versions[PACKAGE_MANIFEST])
  const result: any = { package: "@immune-brain/agent-skills", version: version.toString(), files: Object.keys(versions), valid: true }
  if (tag) {
    const tagVersion = versionFromTag(tag)
    if (tagVersion.compare(version) !== 0) throw new VersionError(`Tag ${tag} does not match manifest version ${version}`)
    result.tag = tag
  }
  return result
}

function printValidate(result: any): void {
  console.log(`package: ${result.package}`)
  console.log(`version: ${result.version}`)
  if (result.tag) console.log(`tag: ${result.tag}`)
  console.log("version_status: aligned")
  console.log("files:")
  for (const path of result.files) console.log(`  - ${path}`)
}

export function main(argv = process.argv.slice(2)): number {
  const { root, rest } = parseGlobalArgs(argv)
  const command = rest.shift()
  try {
    if (command === "stamp") {
      const stamped = stampPluginManifest(root)
      console.log(`package: @immune-brain/agent-skills`)
      console.log(`version: ${stamped.version}`)
      console.log("files:")
      for (const path of stamped.files) console.log(`  - ${path}`)
      return 0
    }
    if (command === "validate") {
      const tagIdx = rest.indexOf("--tag")
      const tag = tagIdx >= 0 ? rest[tagIdx + 1] : undefined
      printValidate(validateManifests(root, tag))
      return 0
    }
    usage()
  } catch (error: any) {
    if (error instanceof VersionError) {
      console.error(`error: ${error.message}`)
      return 2
    }
    throw error
  }
}

if (import.meta.main) process.exit(main())
